---
# This will remove diffie-hellman-group1 (client) sshh_config and (server) sshd_config.
- name: DH Remediation
  hosts: VSPM_DH

  tasks:
    - name: Adding good protocols to EOF of ssh.config
      ansible.builtin.lineinfile:
        path: '/etc/ssh/ssh_config'
        line: '        KexAlgorithms diffie-hellman-group14-sha1,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group-exchange-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,curve25519-sha256,curve25519-sha256\@libssh.org,gss-gex-sha1-,gss-group1-sha1-,gss-group14-sha1-'
        insertafter: EOF
        backup: true

    - name: Adding good protocols to EOF of sshd.config
      ansible.builtin.lineinfile:
        path: '/etc/ssh/sshd_config'
        line: 'KexAlgorithms gss-gex-sha1-,gss-group1-sha1-,gss-group14-sha1-,curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1'
        insertafter: '^.*override default of no subsystems$'
        backup: true

    - name: restart sshd service
      ansible.builtin.service:
       name: httpd
       state: restarted